const APP_STORAGE_KEY="kinshima-scoreboard-v6";
const LEGACY_KEYS=["kinshima-scoreboard-v4","kinshima-scoreboard-v3","royal-scoreboard-v2","royal-scoreboard-v1"];
const ADMIN_SESSION_KEY="kinshima-admin-session";
const ADMIN_SECURITY_KEY="kinshima-admin-security";
const ADMIN_FALLBACK_PASSWORD="Kinshima-Admin-2026";
const ADMIN_PASSWORD_API_ENDPOINT="/api/admin-password";
const MAX_LOGIN_ATTEMPTS=5;
const LOCKOUT_MS=5*60*1000;
const MAX_LOGO_FILE_SIZE=1500000;
const TEAM_COLOR_PALETTE=["#3f6de0","#f39c12","#2ecc71","#e74c3c","#9b59b6","#1abc9c","#f1c40f"];
const DEFAULT_TEAM_PRESETS=[{name:"Alphanos",color:"#3f6de0",logo:"logos/Alphanos.png"},{name:"Arturok",color:"#f39c12",logo:"logos/Arturok.png"},{name:"Bragnir",color:"#2ecc71",logo:"logos/Bragnir.png"},{name:"O-Tsuyujin",color:"#e74c3c",logo:"logos/O-Tsuyujin.png"},{name:"Seklan",color:"#9b59b6",logo:"logos/Seklan.png"},{name:"Son-Enma",color:"#1abc9c",logo:"logos/Son-Enma.png"}];
const MARTIAL_CATEGORIES=["Petits","Moyens","Grands","Kinyobis","Chefs de clan"];
const NARRATIVE_CATEGORIES=["Missions","Quetes","Craft","Duel","Hugen"];
const DEFAULT_CATEGORIES=[...MARTIAL_CATEGORIES,...NARRATIVE_CATEGORIES];
const DEFAULT_TAGS=["Sans tag"];
const MARTIAL_CATEGORY_SET=new Set(MARTIAL_CATEGORIES);
const NARRATIVE_CATEGORY_SET=new Set(NARRATIVE_CATEGORIES);
const LEGACY_CATEGORY_MAP={"puissance":"Petits","technique":"Moyens","discipline":"Grands"};
const CATEGORY_CANONICAL_MAP=DEFAULT_CATEGORIES.reduce((acc,category)=>{acc[category.toLowerCase()]=category;return acc;},{...LEGACY_CATEGORY_MAP});
const defaultState={teams:DEFAULT_TEAM_PRESETS.map((preset)=>preset.name),categories:[...DEFAULT_CATEGORIES],tags:[...DEFAULT_TAGS],teamStyles:DEFAULT_TEAM_PRESETS.reduce((acc,preset)=>{acc[preset.name]={color:preset.color,logo:preset.logo};return acc;},{}),entries:[{season:"LK26",team:"Alphanos",category:"Petits",tag:"Competition generale",score:22,note:"Combat d'ouverture",occurredAt:"2026-03-01T18:30"},{season:"LK26",team:"Arturok",category:"Moyens",tag:"Competition generale",score:17,note:"Tour 1",occurredAt:"2026-03-02T19:10"},{season:"LK26",team:"Bragnir",category:"Grands",tag:"Competition generale",score:19,note:"Tour 1",occurredAt:"2026-03-02T20:05"},{season:"LK26",team:"O-Tsuyujin",category:"Missions",tag:"Campagne narrative",score:14,note:"Tour 1",occurredAt:"2026-03-03T18:40"},{season:"LK26",team:"Seklan",category:"Duel",tag:"Campagne narrative",score:27,note:"Tour 1",occurredAt:"2026-03-03T21:15"},{season:"LK26",team:"Son-Enma",category:"Craft",tag:"Campagne narrative",score:23,note:"Tour 1",occurredAt:"2026-03-04T19:25"}]};
const state=loadAppState();let security=loadSecurityState();
const rankingHead=document.getElementById("ranking-head");const rankingBody=document.getElementById("ranking-body");const historyBody=document.getElementById("history-body");
const seasonProgressChart=document.getElementById("season-progress-chart");const globalPointsChart=document.getElementById("global-points-chart");
const activeSeasonSelect=document.getElementById("active-season");const scoreScopeSelect=document.getElementById("score-scope");const activeCategorySelect=document.getElementById("active-category");const activeTagSelect=document.getElementById("active-tag");const filterSeason=document.getElementById("filter-season");const filterTeam=document.getElementById("filter-team");const filterCategory=document.getElementById("filter-category");const filterTag=document.getElementById("filter-tag");
const seasonProgressTitle=document.getElementById("season-progress-title");const globalPointsTitle=document.getElementById("global-points-title");
const adminLocked=document.getElementById("admin-locked");const adminUnlocked=document.getElementById("admin-unlocked");const adminLogout=document.getElementById("admin-logout");const adminLoginForm=document.getElementById("admin-login-form");const adminPasswordInput=document.getElementById("admin-password");const adminLockInfo=document.getElementById("admin-lock-info");const adminLoginError=document.getElementById("admin-login-error");const adminFeedback=document.getElementById("admin-feedback");
const scoreForm=document.getElementById("score-form");const seasonInput=document.getElementById("season");const seasonsList=document.getElementById("seasons-list");const teamSelect=document.getElementById("team");const categorySelect=document.getElementById("category");const tagSelect=document.getElementById("tag");const scoreInput=document.getElementById("score");const noteInput=document.getElementById("note");const occurredAtInput=document.getElementById("occurred-at");
const adminResultsBody=document.getElementById("admin-results-body");
const adminResultsPageSizeSelect=document.getElementById("admin-results-page-size");const adminResultsPrevButton=document.getElementById("admin-results-prev");const adminResultsNextButton=document.getElementById("admin-results-next");const adminResultsPageInfo=document.getElementById("admin-results-page-info");const adminResultsTotal=document.getElementById("admin-results-total");const adminResultsExportCsvButton=document.getElementById("admin-results-export-csv");const adminResultsImportCsvButton=document.getElementById("admin-results-import-csv");const adminResultsImportFileInput=document.getElementById("admin-results-import-file");const adminResultsImportModeSelect=document.getElementById("admin-results-import-mode");
const teamRenameForm=document.getElementById("team-rename-form");const teamRenameSelect=document.getElementById("team-rename-select");const teamRenameInput=document.getElementById("team-rename-input");const teamAddForm=document.getElementById("team-add-form");const teamAddInput=document.getElementById("team-add-input");const teamDeleteForm=document.getElementById("team-delete-form");const teamDeleteSelect=document.getElementById("team-delete-select");
const teamStyleForm=document.getElementById("team-style-form");const teamStyleSelect=document.getElementById("team-style-select");const teamColorInput=document.getElementById("team-color-input");const teamLogoInput=document.getElementById("team-logo-input");const teamLogoRemoveButton=document.getElementById("team-logo-remove");
const categoryRenameForm=document.getElementById("category-rename-form");const categoryRenameSelect=document.getElementById("category-rename-select");const categoryRenameInput=document.getElementById("category-rename-input");const categoryAddForm=document.getElementById("category-add-form");const categoryAddInput=document.getElementById("category-add-input");const categoryDeleteForm=document.getElementById("category-delete-form");const categoryDeleteSelect=document.getElementById("category-delete-select");
const tagRenameForm=document.getElementById("tag-rename-form");const tagRenameSelect=document.getElementById("tag-rename-select");const tagRenameInput=document.getElementById("tag-rename-input");const tagAddForm=document.getElementById("tag-add-form");const tagAddInput=document.getElementById("tag-add-input");const tagDeleteForm=document.getElementById("tag-delete-form");const tagDeleteSelect=document.getElementById("tag-delete-select");
const passwordChangeForm=document.getElementById("admin-password-change-form");const currentPasswordInput=document.getElementById("admin-current-password");const newPasswordInput=document.getElementById("admin-new-password");const confirmPasswordInput=document.getElementById("admin-confirm-password");
const hasPublicView=Boolean(rankingHead&&rankingBody&&historyBody);const hasAdminView=Boolean(adminLocked&&adminUnlocked&&adminLoginForm);let lockTimerId=null;let securitySyncTimerId=null;let adminResultsPage=1;
initialize();
async function initialize(){hydrateEntries();normalizeTeamStyles();await bootstrapEntriesStorage();await migrateLegacyCategoriesIfNeeded();const categoriesChanged=ensureBaseCategories();const tagsChanged=ensureBaseTags();if(categoriesChanged||tagsChanged)saveState();await hydrateSecurityState();await hydrateSecurityFromServer();if(occurredAtInput&&!occurredAtInput.value){occurredAtInput.value=getNowLocalDateTimeValue();}refreshAllControls(getCurrentSeasonCode());if(hasPublicView){enforceScopeFilterCompatibility();renderAll();}if(hasAdminView){syncAdminUI();syncTeamStyleInputs();renderAdminResultsManager();startSecuritySyncTicker();}wireEvents();if(hasPublicView)window.addEventListener("resize",()=>renderCharts());}
function wireEvents(){if(activeSeasonSelect)activeSeasonSelect.addEventListener("change",renderAll);if(activeCategorySelect)activeCategorySelect.addEventListener("change",renderAll);if(activeTagSelect)activeTagSelect.addEventListener("change",renderAll);if(scoreScopeSelect)scoreScopeSelect.addEventListener("change",()=>{enforceScopeFilterCompatibility();renderAll();});if(filterSeason)filterSeason.addEventListener("change",renderHistory);if(filterTeam)filterTeam.addEventListener("change",renderHistory);if(filterCategory)filterCategory.addEventListener("change",renderHistory);if(filterTag)filterTag.addEventListener("change",renderHistory);if(adminLoginForm)adminLoginForm.addEventListener("submit",handleAdminLogin);if(adminLogout)adminLogout.addEventListener("click",handleAdminLogout);if(scoreForm)scoreForm.addEventListener("submit",handleScoreSubmit);if(adminResultsBody)adminResultsBody.addEventListener("click",handleAdminResultsAction);if(adminResultsPageSizeSelect)adminResultsPageSizeSelect.addEventListener("change",handleAdminResultsPageSizeChange);if(adminResultsPrevButton)adminResultsPrevButton.addEventListener("click",()=>changeAdminResultsPage(-1));if(adminResultsNextButton)adminResultsNextButton.addEventListener("click",()=>changeAdminResultsPage(1));if(adminResultsExportCsvButton)adminResultsExportCsvButton.addEventListener("click",handleExportResultsCsv);if(adminResultsImportCsvButton)adminResultsImportCsvButton.addEventListener("click",()=>adminResultsImportFileInput?.click());if(adminResultsImportFileInput)adminResultsImportFileInput.addEventListener("change",handleImportResultsCsv);if(teamAddForm)teamAddForm.addEventListener("submit",handleTeamAdd);if(teamRenameForm)teamRenameForm.addEventListener("submit",handleTeamRename);if(teamDeleteForm)teamDeleteForm.addEventListener("submit",handleTeamDelete);if(teamStyleForm)teamStyleForm.addEventListener("submit",handleTeamStyleSave);if(teamStyleSelect)teamStyleSelect.addEventListener("change",syncTeamStyleInputs);if(teamLogoRemoveButton)teamLogoRemoveButton.addEventListener("click",handleTeamLogoRemove);if(categoryAddForm)categoryAddForm.addEventListener("submit",handleCategoryAdd);if(categoryRenameForm)categoryRenameForm.addEventListener("submit",handleCategoryRename);if(categoryDeleteForm)categoryDeleteForm.addEventListener("submit",handleCategoryDelete);if(tagAddForm)tagAddForm.addEventListener("submit",handleTagAdd);if(tagRenameForm)tagRenameForm.addEventListener("submit",handleTagRename);if(tagDeleteForm)tagDeleteForm.addEventListener("submit",handleTagDelete);if(passwordChangeForm)passwordChangeForm.addEventListener("submit",handlePasswordChange);}
async function handleAdminLogin(e){e.preventDefault();await hydrateSecurityFromServer();if(isLockedOut()){showLoginError(lockoutMessage());return;}const submitted=adminPasswordInput.value;if(submitted===security.password){security.failCount=0;security.lockedUntil=0;saveSecurityState();localStorage.setItem(ADMIN_SESSION_KEY,"1");adminPasswordInput.value="";adminLoginError.classList.add("hidden");syncAdminUI();return;}security.failCount+=1;if(security.failCount>=MAX_LOGIN_ATTEMPTS){security.lockedUntil=Date.now()+LOCKOUT_MS;security.failCount=0;showLoginError(lockoutMessage());}else{showLoginError(`Mot de passe invalide. Tentatives restantes: ${MAX_LOGIN_ATTEMPTS-security.failCount}.`);}saveSecurityState();}
function handleAdminLogout(){localStorage.removeItem(ADMIN_SESSION_KEY);syncAdminUI();}
async function handleScoreSubmit(e){e.preventDefault();if(!isAdmin())return;const season=normalizeSeasonCode(seasonInput.value);const team=teamSelect.value;const category=categorySelect.value;const tag=canonicalTagName(tagSelect?.value)||DEFAULT_TAGS[0];const score=Number(scoreInput.value);const note=noteInput.value.trim();const occurredAt=normalizeDateTimeInput(occurredAtInput.value);if(!season){showAdminFeedback("Format saison invalide. Utilise LK26, LK27, etc.","error");return;}if(!team||!category||!tag||Number.isNaN(score)||score<0||!occurredAt){showAdminFeedback("Tous les champs de score sont obligatoires.","error");return;}state.entries.unshift({id:createEntryId(),season,team,category,tag,score,note,occurredAt});await persistEntries();if(scoreInput)scoreInput.value="";if(noteInput)noteInput.value="";if(occurredAtInput)occurredAtInput.value=getNowLocalDateTimeValue();if(seasonInput)seasonInput.value=season;refreshAllControls(season);renderAll();showAdminFeedback("Score ajoute.","success");}
function handleTeamAdd(e){e.preventDefault();if(!isAdmin())return;const newName=sanitizeName(teamAddInput.value);if(!newName){showAdminFeedback("Nom de clan invalide.","error");return;}if(hasName(state.teams,newName)){showAdminFeedback("Ce clan existe deja.","error");return;}state.teams.push(newName);state.teamStyles[newName]={color:getDefaultTeamColor(state.teams.length-1),logo:""};teamAddInput.value="";saveState();refreshAllControls(activeSeasonSelect?activeSeasonSelect.value:getCurrentSeasonCode());syncTeamStyleInputs();renderAll();showAdminFeedback("Clan ajoute.","success");}
async function handleTeamRename(e){e.preventDefault();if(!isAdmin())return;const oldName=teamRenameSelect.value;const newName=sanitizeName(teamRenameInput.value);if(!oldName||!newName||normalizeText(oldName)===normalizeText(newName)){showAdminFeedback("Renommage invalide.","error");return;}if(hasName(state.teams,newName)){showAdminFeedback("Un clan avec ce nom existe deja.","error");return;}state.teams=state.teams.map((t)=>t===oldName?newName:t);state.entries=state.entries.map((entry)=>({...entry,team:entry.team===oldName?newName:entry.team}));state.teamStyles[newName]=state.teamStyles[oldName]||{color:getDefaultTeamColor(0),logo:""};delete state.teamStyles[oldName];teamRenameInput.value="";await persistEntries();refreshAllControls(activeSeasonSelect?activeSeasonSelect.value:getCurrentSeasonCode());syncTeamStyleInputs();renderAll();showAdminFeedback("Clan renomme.","success");}
function handleTeamDelete(e){e.preventDefault();if(!isAdmin())return;const target=teamDeleteSelect.value;if(!target){showAdminFeedback("Selectionne un clan a supprimer.","error");return;}if(state.teams.length<=1){showAdminFeedback("Impossible: il faut garder au moins un clan.","error");return;}if(state.entries.some((entry)=>entry.team===target)){showAdminFeedback("Impossible de supprimer ce clan: des scores lui sont associes.","error");return;}state.teams=state.teams.filter((t)=>t!==target);delete state.teamStyles[target];saveState();refreshAllControls(activeSeasonSelect?activeSeasonSelect.value:getCurrentSeasonCode());syncTeamStyleInputs();renderAll();showAdminFeedback("Clan supprime.","success");}
async function handleTeamStyleSave(e){e.preventDefault();if(!isAdmin())return;const team=teamStyleSelect.value;if(!team){showAdminFeedback("Selectionne un clan.","error");return;}const current=getTeamStyle(team);const color=sanitizeHexColor(teamColorInput.value,current.color);let logo=current.logo;const file=teamLogoInput.files?.[0];if(file){if(file.size>MAX_LOGO_FILE_SIZE){showAdminFeedback("Logo trop lourd (max 1.5 MB).","error");return;}try{logo=await readFileAsDataUrl(file);}catch{showAdminFeedback("Impossible de lire le fichier logo.","error");return;}}state.teamStyles[team]={color,logo:logo||""};saveState();teamLogoInput.value="";renderAll();showAdminFeedback("Style du clan mis a jour.","success");}
function handleTeamLogoRemove(){if(!isAdmin())return;const team=teamStyleSelect.value;if(!team)return;const current=getTeamStyle(team);state.teamStyles[team]={color:current.color,logo:""};saveState();teamLogoInput.value="";renderAll();showAdminFeedback("Logo retire.","success");}
function handleCategoryAdd(e){e.preventDefault();if(!isAdmin())return;ensureTaxonomyState();const newName=canonicalCategoryName(categoryAddInput.value);if(!newName){showAdminFeedback("Nom de categorie invalide.","error");return;}if(hasName(state.categories,newName)){showAdminFeedback("Cette categorie existe deja.","error");return;}state.categories.push(newName);categoryAddInput.value="";saveState();refreshAllControls(activeSeasonSelect?activeSeasonSelect.value:getCurrentSeasonCode());renderAll();showAdminFeedback("Categorie ajoutee.","success");}
async function handleCategoryRename(e){e.preventDefault();if(!isAdmin())return;ensureTaxonomyState();const oldName=categoryRenameSelect.value;const newName=canonicalCategoryName(categoryRenameInput.value);if(!oldName||!newName||normalizeText(oldName)===normalizeText(newName)){showAdminFeedback("Renommage invalide.","error");return;}if(hasName(state.categories,newName)){showAdminFeedback("Une categorie avec ce nom existe deja.","error");return;}state.categories=state.categories.map((c)=>c===oldName?newName:c);state.entries=state.entries.map((entry)=>({...entry,category:entry.category===oldName?newName:entry.category}));categoryRenameInput.value="";await persistEntries();refreshAllControls(activeSeasonSelect?activeSeasonSelect.value:getCurrentSeasonCode());renderAll();showAdminFeedback("Categorie renommee.","success");}
function handleCategoryDelete(e){e.preventDefault();if(!isAdmin())return;ensureTaxonomyState();const target=categoryDeleteSelect.value;if(!target){showAdminFeedback("Selectionne une categorie a supprimer.","error");return;}if(state.categories.length<=1){showAdminFeedback("Impossible: il faut garder au moins une categorie.","error");return;}if(state.entries.some((entry)=>entry.category===target)){showAdminFeedback("Impossible de supprimer cette categorie: des scores y sont associes.","error");return;}state.categories=state.categories.filter((c)=>c!==target);saveState();refreshAllControls(activeSeasonSelect?activeSeasonSelect.value:getCurrentSeasonCode());renderAll();showAdminFeedback("Categorie supprimee.","success");}
function handleTagAdd(e){e.preventDefault();if(!isAdmin())return;ensureTaxonomyState();const newName=canonicalTagName(tagAddInput.value);if(!newName){showAdminFeedback("Nom de tag invalide.","error");return;}if(hasName(state.tags,newName)){showAdminFeedback("Ce tag existe deja.","error");return;}state.tags.push(newName);tagAddInput.value="";saveState();refreshAllControls(activeSeasonSelect?activeSeasonSelect.value:getCurrentSeasonCode());renderAll();showAdminFeedback("Tag ajoute.","success");}
async function handleTagRename(e){e.preventDefault();if(!isAdmin())return;ensureTaxonomyState();const oldName=tagRenameSelect.value;const newName=canonicalTagName(tagRenameInput.value);if(!oldName||!newName||normalizeText(oldName)===normalizeText(newName)){showAdminFeedback("Renommage invalide.","error");return;}if(hasName(state.tags,newName)){showAdminFeedback("Un tag avec ce nom existe deja.","error");return;}state.tags=state.tags.map((tag)=>tag===oldName?newName:tag);state.entries=state.entries.map((entry)=>({...entry,tag:entry.tag===oldName?newName:entry.tag}));tagRenameInput.value="";await persistEntries();refreshAllControls(activeSeasonSelect?activeSeasonSelect.value:getCurrentSeasonCode());renderAll();showAdminFeedback("Tag renomme.","success");}
function handleTagDelete(e){e.preventDefault();if(!isAdmin())return;ensureTaxonomyState();const target=tagDeleteSelect.value;if(!target){showAdminFeedback("Selectionne un tag a supprimer.","error");return;}if(state.tags.length<=1){showAdminFeedback("Impossible: il faut garder au moins un tag.","error");return;}if(state.entries.some((entry)=>entry.tag===target)){showAdminFeedback("Impossible de supprimer ce tag: des scores y sont associes.","error");return;}state.tags=state.tags.filter((tag)=>tag!==target);saveState();refreshAllControls(activeSeasonSelect?activeSeasonSelect.value:getCurrentSeasonCode());renderAll();showAdminFeedback("Tag supprime.","success");}
async function handlePasswordChange(e){e.preventDefault();if(!isAdmin())return;await hydrateSecurityFromServer();const currentPassword=currentPasswordInput.value;const newPassword=newPasswordInput.value;const confirmPassword=confirmPasswordInput.value;if(currentPassword!==security.password){showAdminFeedback("Mot de passe actuel incorrect.","error");return;}if(newPassword.length<8){showAdminFeedback("Le nouveau mot de passe doit contenir au moins 8 caracteres.","error");return;}if(newPassword!==confirmPassword){showAdminFeedback("La confirmation du nouveau mot de passe ne correspond pas.","error");return;}security.password=newPassword;security.failCount=0;security.lockedUntil=0;saveSecurityState();const synced=await pushSecurityToServer();passwordChangeForm.reset();showAdminFeedback(synced?"Mot de passe admin mis a jour (global).":"Mot de passe mis a jour localement. Configure /api/admin-password pour le mode global.",synced?"success":"error");}
function syncAdminUI(){if(!hasAdminView)return;const unlocked=isAdmin();adminLocked.classList.toggle("hidden",unlocked);adminUnlocked.classList.toggle("hidden",!unlocked);adminLogout.classList.toggle("hidden",!unlocked);if(unlocked){adminLoginError.classList.add("hidden");adminLockInfo.textContent="Session admin active.";}else{adminPasswordInput.value="";if(isLockedOut()){showLoginError(lockoutMessage());}else{adminLoginError.classList.add("hidden");adminLockInfo.textContent=`5 erreurs consecutives bloquent l'acces 5 minutes. Tentatives restantes: ${Math.max(0,MAX_LOGIN_ATTEMPTS-security.failCount)}.`;}}setupLockoutTicker();}
function setupLockoutTicker(){if(lockTimerId){clearInterval(lockTimerId);lockTimerId=null;}if(!isLockedOut())return;lockTimerId=setInterval(()=>{if(!isLockedOut()){clearInterval(lockTimerId);lockTimerId=null;adminLoginError.classList.add("hidden");adminLockInfo.textContent="Le verrouillage est termine. Tu peux reessayer.";return;}showLoginError(lockoutMessage());},1000);}
function showLoginError(message){if(!adminLoginError||!adminLockInfo)return;adminLoginError.textContent=message;adminLoginError.classList.remove("hidden");adminLockInfo.textContent=message;}
function lockoutMessage(){return `Acces temporairement bloque. Reessaie dans ${Math.max(1,Math.ceil((security.lockedUntil-Date.now())/1000))}s.`;}
function isLockedOut(){return Number(security.lockedUntil||0)>Date.now();}
function isAdmin(){return localStorage.getItem(ADMIN_SESSION_KEY)==="1";}
function refreshAllControls(preferredSeason){refreshSeasonControls(preferredSeason);refreshTeamControls();refreshCategoryControls();refreshTagControls();renderAdminResultsManager();}
function refreshSeasonControls(preferredSeason){const seasons=getSeasonList(state.entries);const previousActive=activeSeasonSelect?activeSeasonSelect.value:"";const previousFilter=filterSeason?filterSeason.value:"";if(seasonsList){seasonsList.innerHTML="";seasons.forEach((season)=>{const option=document.createElement("option");option.value=season;seasonsList.appendChild(option);});}if(activeSeasonSelect){fillSelect(activeSeasonSelect,seasons,{includeAll:true,allLabel:"Toutes"});activeSeasonSelect.value=chooseSelectValue(activeSeasonSelect,[preferredSeason,previousActive,getCurrentSeasonCode(),"all"]);}if(filterSeason){fillSelect(filterSeason,seasons,{includeAll:true,allLabel:"Toutes"});filterSeason.value=chooseSelectValue(filterSeason,[preferredSeason,previousFilter,"all"]);}if(seasonInput&&!seasonInput.value)seasonInput.value=getCurrentSeasonCode();}
function refreshTeamControls(){fillSelect(teamSelect,state.teams);fillSelect(teamRenameSelect,state.teams);fillSelect(teamDeleteSelect,state.teams);fillSelect(teamStyleSelect,state.teams);fillSelect(filterTeam,state.teams,{includeAll:true,allLabel:"Tous"});syncTeamStyleInputs();}
function refreshCategoryControls(){ensureTaxonomyState();const ordered=getOrderedCategories();fillCategorySelect(categorySelect,ordered);fillCategorySelect(categoryRenameSelect,ordered);fillCategorySelect(categoryDeleteSelect,ordered);fillCategorySelect(activeCategorySelect,ordered,{includeAll:true,allLabel:"Toutes"});fillCategorySelect(filterCategory,ordered,{includeAll:true,allLabel:"Toutes"});}
function refreshTagControls(){ensureTaxonomyState();const ordered=getOrderedTags();fillSelect(tagSelect,ordered);fillSelect(tagRenameSelect,ordered);fillSelect(tagDeleteSelect,ordered);fillSelect(activeTagSelect,ordered,{includeAll:true,allLabel:"Tous"});fillSelect(filterTag,ordered,{includeAll:true,allLabel:"Tous"});}
function syncTeamStyleInputs(){if(!teamStyleSelect||!teamColorInput)return;const team=teamStyleSelect.value;if(!team)return;teamColorInput.value=sanitizeHexColor(getTeamStyle(team).color,getDefaultTeamColor(0));}
function fillSelect(selectElement,values,options={}){if(!selectElement)return;const {includeAll=false,allLabel="Toutes"}=options;const previousValue=selectElement.value;selectElement.innerHTML="";if(includeAll)addOption(selectElement,"all",allLabel);values.forEach((value)=>addOption(selectElement,value,value));selectElement.value=chooseSelectValue(selectElement,[previousValue,includeAll?"all":values[0]]);}
function fillCategorySelect(selectElement,values,options={}){if(!selectElement)return;const {includeAll=false,allLabel="Toutes"}=options;const previousValue=selectElement.value;selectElement.innerHTML="";if(includeAll)addOption(selectElement,"all",allLabel);const martial=values.filter((value)=>isMartialCategory(value));const narrative=values.filter((value)=>isNarrativeCategory(value));const others=values.filter((value)=>!isMartialCategory(value)&&!isNarrativeCategory(value));addCategoryGroup(selectElement,"Categories martiales",martial);addCategoryGroup(selectElement,"Categories narratives",narrative);others.forEach((value)=>addOption(selectElement,value,value));selectElement.value=chooseSelectValue(selectElement,[previousValue,includeAll?"all":values[0]]);}
function addCategoryGroup(selectElement,label,values){if(!values.length)return;const group=document.createElement("optgroup");group.label=label;values.forEach((value)=>{const option=document.createElement("option");option.value=value;option.textContent=value;group.appendChild(option);});selectElement.appendChild(group);}
function getCategoryOptionsHtml(values,selectedValue){const buildOption=(value)=>`<option value="${escapeAttr(value)}"${value===selectedValue?" selected":""}>${escapeHtml(value)}</option>`;const martial=values.filter((value)=>isMartialCategory(value));const narrative=values.filter((value)=>isNarrativeCategory(value));const others=values.filter((value)=>!isMartialCategory(value)&&!isNarrativeCategory(value));let html="";if(martial.length)html+=`<optgroup label="Categories martiales">${martial.map(buildOption).join("")}</optgroup>`;if(narrative.length)html+=`<optgroup label="Categories narratives">${narrative.map(buildOption).join("")}</optgroup>`;if(others.length)html+=others.map(buildOption).join("");return html;}
function addOption(selectElement,value,label){const option=document.createElement("option");option.value=value;option.textContent=label;selectElement.appendChild(option);}
function chooseSelectValue(selectElement,candidates){const values=new Set(Array.from(selectElement.options,(option)=>option.value));for(const candidate of candidates){if(candidate&&values.has(candidate))return candidate;}return selectElement.options[0]?.value||"";}
function renderAll(){if(!hasPublicView)return;renderRanking();renderHistory();renderCharts();}
function renderAdminResultsManager(){if(!adminResultsBody)return;const rows=[...state.entries].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));const categories=getOrderedCategories();const tags=getOrderedTags();const pageSize=getAdminResultsPageSize();const total=rows.length;const totalPages=Math.max(1,Math.ceil(total/pageSize));adminResultsPage=Math.min(Math.max(1,adminResultsPage),totalPages);const start=(adminResultsPage-1)*pageSize;const pagedRows=rows.slice(start,start+pageSize);if(adminResultsTotal)adminResultsTotal.textContent=`${total} resultat${total>1?"s":""}`;if(adminResultsPageInfo)adminResultsPageInfo.textContent=`Page ${adminResultsPage} / ${totalPages}`;if(adminResultsPrevButton)adminResultsPrevButton.disabled=adminResultsPage<=1;if(adminResultsNextButton)adminResultsNextButton.disabled=adminResultsPage>=totalPages;adminResultsBody.innerHTML="";if(!pagedRows.length){const tr=document.createElement("tr");tr.innerHTML='<td colspan="8" class="empty">Aucun resultat enregistre.</td>';adminResultsBody.appendChild(tr);return;}pagedRows.forEach((entry)=>{const tr=document.createElement("tr");tr.dataset.entryId=entry.id;tr.innerHTML=`<td data-label="Date/Heure"><input type="datetime-local" class="admin-result-occurred-at" value="${escapeAttr(normalizeDateTimeInput(entry.occurredAt)||getNowLocalDateTimeValue())}" /></td><td data-label="Saison"><input type="text" class="admin-result-season" value="${escapeAttr(entry.season)}" maxlength="4" /></td><td data-label="Clan"><select class="admin-result-team">${state.teams.map((team)=>`<option value="${escapeAttr(team)}"${team===entry.team?" selected":""}>${escapeHtml(team)}</option>`).join("")}</select></td><td data-label="Categorie"><select class="admin-result-category">${getCategoryOptionsHtml(categories,entry.category)}</select></td><td data-label="Tag"><select class="admin-result-tag">${tags.map((tag)=>`<option value="${escapeAttr(tag)}"${tag===entry.tag?" selected":""}>${escapeHtml(tag)}</option>`).join("")}</select></td><td data-label="Score"><input type="number" class="admin-result-score" min="0" max="1000" value="${entry.score}" /></td><td data-label="Note"><input type="text" class="admin-result-note" maxlength="80" value="${escapeAttr(entry.note||"")}" /></td><td data-label="Actions"><div class="actions"><button type="button" data-action="save">Enregistrer</button><button type="button" data-action="delete" class="ghost">Supprimer</button></div></td>`;adminResultsBody.appendChild(tr);});}
function getAdminResultsPageSize(){const raw=Number(adminResultsPageSizeSelect?.value||20);if(!Number.isFinite(raw)||raw<=0)return 20;return Math.floor(raw);}
function handleAdminResultsPageSizeChange(){adminResultsPage=1;renderAdminResultsManager();}
function changeAdminResultsPage(delta){adminResultsPage=Math.max(1,adminResultsPage+delta);renderAdminResultsManager();}
async function handleAdminResultsAction(e){if(!isAdmin())return;const button=e.target.closest("button[data-action]");if(!button)return;const row=button.closest("tr[data-entry-id]");if(!row)return;const entryId=row.dataset.entryId;const index=state.entries.findIndex((entry)=>entry.id===entryId);if(index<0){showAdminFeedback("Resultat introuvable.","error");return;}if(button.dataset.action==="delete"){const ok=window.confirm("Supprimer ce resultat ?");if(!ok)return;state.entries.splice(index,1);await persistEntries();refreshAllControls(getCurrentSeasonCode());renderAll();showAdminFeedback("Resultat supprime.","success");return;}if(button.dataset.action!=="save")return;const season=normalizeSeasonCode(row.querySelector(".admin-result-season")?.value);const team=row.querySelector(".admin-result-team")?.value||"";const category=row.querySelector(".admin-result-category")?.value||"";const tag=canonicalTagName(row.querySelector(".admin-result-tag")?.value)||DEFAULT_TAGS[0];const score=Number(row.querySelector(".admin-result-score")?.value);const note=(row.querySelector(".admin-result-note")?.value||"").trim();const occurredAt=normalizeDateTimeInput(row.querySelector(".admin-result-occurred-at")?.value);if(!season||!team||!category||!tag||Number.isNaN(score)||score<0||!occurredAt){showAdminFeedback("Champs invalides pour ce resultat.","error");return;}state.entries[index]={...state.entries[index],season,team,category,tag,score,note,occurredAt};await persistEntries();refreshAllControls(season);renderAll();showAdminFeedback("Resultat mis a jour.","success");}
function handleExportResultsCsv(){if(!state.entries.length){showAdminFeedback("Aucun resultat a exporter.","error");return;}const rows=[...state.entries].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));const headers=["id","occurredAt","season","team","category","tag","score","note"];const csv=[headers.join(",")].concat(rows.map((entry)=>headers.map((key)=>escapeCsvCell(entry[key])).join(","))).join("\n");const blob=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8;"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`kinshima-results-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);showAdminFeedback("Export CSV genere.","success");}
async function handleImportResultsCsv(e){if(!isAdmin())return;const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();const imported=parseResultsCsv(text);if(!imported.length){showAdminFeedback("CSV invalide ou vide.","error");return;}const mode=adminResultsImportModeSelect?.value==="replace"?"replace":"merge";const confirmed=window.confirm(mode==="replace"?`Importer ${imported.length} resultats et remplacer la base actuelle ?`:`Importer ${imported.length} resultats en mode fusion (ajout/mise a jour) ?`);if(!confirmed)return;const importedEntries=imported.map((entry)=>normalizeEntry(entry));importedEntries.forEach((entry)=>{if(entry.team&&!state.teams.includes(entry.team)){state.teams.push(entry.team);state.teamStyles[entry.team]={color:getDefaultTeamColor(state.teams.length-1),logo:""};}if(entry.category&&!state.categories.includes(entry.category)){state.categories.push(entry.category);}if(entry.tag&&!state.tags.includes(entry.tag)){state.tags.push(entry.tag);}});state.entries=mode==="replace"?importedEntries:mergeImportedEntries(state.entries,importedEntries);await persistEntries();refreshAllControls(getCurrentSeasonCode());renderAll();showAdminFeedback(mode==="replace"?"Import CSV termine (remplacement).":"Import CSV termine (fusion).","success");}catch{showAdminFeedback("Erreur pendant l'import CSV.","error");}finally{if(adminResultsImportFileInput)adminResultsImportFileInput.value="";}}
function renderRanking(){if(!rankingHead||!rankingBody)return;const seasonFilter=activeSeasonSelect?activeSeasonSelect.value:"all";const scope=getSelectedScoreScope();const scopeCategories=getCategoriesForScope(scope);const selectedCategory=getSelectedActiveCategory();const categories=selectedCategory==="all"?scopeCategories:scopeCategories.filter((category)=>category===selectedCategory);const seasonEntries=state.entries.filter((entry)=>seasonFilter==="all"||entry.season===seasonFilter);const scopedEntries=filterEntriesByMainView(seasonEntries,scope);rankingHead.innerHTML="";const totalHeader=scope==="martial"?"Total martial":scope==="narrative"?"Total narratif":"Total global";const headerRow=document.createElement("tr");headerRow.innerHTML=`<th>Clan</th>${categories.map((category)=>`<th>${escapeHtml(category)}</th>`).join("")}<th>${totalHeader}</th><th>Moyenne</th><th>Entrees</th>`;rankingHead.appendChild(headerRow);const stats=state.teams.map((team)=>{const teamEntries=scopedEntries.filter((entry)=>entry.team===team);const categoryScores=categories.map((category)=>teamEntries.filter((entry)=>entry.category===category).reduce((sum,entry)=>sum+entry.score,0));const total=categoryScores.reduce((sum,value)=>sum+value,0);const count=teamEntries.length;const average=count?(total/count).toFixed(1):"0.0";return {team,categoryScores,total,average,count};}).sort((a,b)=>b.total-a.total);rankingBody.innerHTML="";stats.forEach((row)=>{const tr=document.createElement("tr");tr.innerHTML=`<td data-label="Clan">${buildTeamBadgeHtml(row.team)}</td>${row.categoryScores.map((score,index)=>`<td data-label="${escapeAttr(categories[index])}">${score}</td>`).join("")}<td data-label="${escapeAttr(totalHeader)}"><strong>${row.total}</strong></td><td data-label="Moyenne">${row.average}</td><td data-label="Entrees">${row.count}</td>`;rankingBody.appendChild(tr);});}
function renderHistory(){if(!historyBody)return;const scope=getSelectedScoreScope();const seasonFilter=filterSeason?filterSeason.value:"all";const teamFilter=filterTeam?filterTeam.value:"all";const categoryFilter=filterCategory?filterCategory.value:"all";const tagFilter=filterTag?filterTag.value:"all";const rows=filterEntriesByScoreScope(state.entries,scope).filter((entry)=>seasonFilter==="all"||entry.season===seasonFilter).filter((entry)=>teamFilter==="all"||entry.team===teamFilter).filter((entry)=>categoryFilter==="all"||entry.category===categoryFilter).filter((entry)=>tagFilter==="all"||entry.tag===tagFilter).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));historyBody.innerHTML="";if(!rows.length){const tr=document.createElement("tr");tr.innerHTML=`<td colspan="7" class="empty">Aucun resultat pour ce filtre.</td>`;historyBody.appendChild(tr);return;}rows.forEach((entry)=>{const tr=document.createElement("tr");tr.innerHTML=`<td data-label="Saison">${escapeHtml(entry.season)}</td><td data-label="Date/Heure">${formatDateTime(entry.occurredAt)}</td><td data-label="Clan">${buildTeamBadgeHtml(entry.team,true)}</td><td data-label="Categorie">${escapeHtml(entry.category)}</td><td data-label="Tag">${escapeHtml(entry.tag||DEFAULT_TAGS[0])}</td><td data-label="Score">${entry.score}</td><td data-label="Note">${escapeHtml(entry.note||"-")}</td>`;historyBody.appendChild(tr);});}
function renderCharts(){updateChartTitles();drawSeasonProgressChart();drawGlobalPointsChart();}
function drawSeasonProgressChart(){if(!seasonProgressChart)return;const ctx=getCanvasContext(seasonProgressChart);if(!ctx)return;const scope=getSelectedScoreScope();const season=activeSeasonSelect&&activeSeasonSelect.value!=="all"?activeSeasonSelect.value:getSeasonList(state.entries)[0];const rows=filterEntriesByMainView(state.entries,scope).filter((entry)=>entry.season===season).sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt));clearCanvas(ctx);if(!rows.length){drawEmptyCanvasMessage(ctx,"Aucune donnee pour cette vue.");return;}const moments=unique(rows.map((entry)=>entry.occurredAt)).sort();const cumulativeByTeam={};state.teams.forEach((team)=>{let running=0;cumulativeByTeam[team]=moments.map((moment)=>{running+=rows.filter((entry)=>entry.team===team&&entry.occurredAt===moment).reduce((sum,entry)=>sum+entry.score,0);return running;});});const maxY=Math.max(10,...Object.values(cumulativeByTeam).flat());const plot={left:48,right:16,top:20,bottom:36};const {w,h}=getCanvasMetrics(ctx);const pw=w-plot.left-plot.right;const ph=h-plot.top-plot.bottom;drawGrid(ctx,plot,w,h,maxY);const xStep=moments.length>1?pw/(moments.length-1):0;state.teams.forEach((team)=>{const values=cumulativeByTeam[team];if(!values.some((v)=>v>0))return;ctx.strokeStyle=getTeamStyle(team).color;ctx.lineWidth=3;ctx.beginPath();values.forEach((value,i)=>{const x=plot.left+xStep*i;const y=plot.top+ph-(value/maxY)*ph;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();});drawSeasonLegend(ctx,state.teams,plot.left,6);ctx.fillStyle="#d4ddfb";ctx.font="12px Segoe UI";const firstLabel=formatDateTime(moments[0]);const lastLabel=formatDateTime(moments[moments.length-1]);ctx.fillText(firstLabel,plot.left,h-10);ctx.fillText(lastLabel,w-plot.right-ctx.measureText(lastLabel).width,h-10);}
function drawGlobalPointsChart(){if(!globalPointsChart)return;const ctx=getCanvasContext(globalPointsChart);if(!ctx)return;const scope=getSelectedScoreScope();clearCanvas(ctx);const scopedEntries=filterEntriesByMainView(state.entries,scope);const totals=state.teams.map((team)=>({team,total:scopedEntries.filter((entry)=>entry.team===team).reduce((sum,entry)=>sum+entry.score,0)}));const max=Math.max(10,...totals.map((row)=>row.total));const {w,h}=getCanvasMetrics(ctx);const plot={left:46,right:16,top:18,bottom:48};const pw=w-plot.left-plot.right;const ph=h-plot.top-plot.bottom;drawGrid(ctx,plot,w,h,max);const barGap=20;const barWidth=Math.max(26,(pw-barGap*(totals.length-1))/Math.max(1,totals.length));totals.forEach((row,i)=>{const x=plot.left+i*(barWidth+barGap);const height=(row.total/max)*ph;const y=plot.top+ph-height;const style=getTeamStyle(row.team);ctx.fillStyle=style.color;ctx.fillRect(x,y,barWidth,height);ctx.fillStyle="#f5f7ff";ctx.font="12px Segoe UI";const valueText=String(row.total);ctx.fillText(valueText,x+(barWidth-ctx.measureText(valueText).width)/2,y-6);const label=row.team.length>9?`${row.team.slice(0,8)}.`:row.team;ctx.fillText(label,x+(barWidth-ctx.measureText(label).width)/2,h-14);});}
function drawGrid(ctx,plot,w,h,maxY){const pw=w-plot.left-plot.right;const ph=h-plot.top-plot.bottom;ctx.strokeStyle="rgba(231, 191, 90, 0.22)";ctx.lineWidth=1;for(let i=0;i<=5;i+=1){const y=plot.top+(ph/5)*i;ctx.beginPath();ctx.moveTo(plot.left,y);ctx.lineTo(plot.left+pw,y);ctx.stroke();const value=Math.round(maxY-(maxY/5)*i);ctx.fillStyle="#c9d3f8";ctx.font="11px Segoe UI";ctx.fillText(String(value),8,y+4);}}
function drawSeasonLegend(ctx,teams,xStart,yStart){let x=xStart;teams.forEach((team)=>{const style=getTeamStyle(team);ctx.fillStyle=style.color;ctx.fillRect(x,yStart,12,12);ctx.fillStyle="#e8eeff";ctx.font="12px Segoe UI";ctx.fillText(team,x+16,yStart+10);x+=16+ctx.measureText(team).width+12;});}
function getCanvasContext(canvas){if(!canvas)return null;const dpr=window.devicePixelRatio||1;const rect=canvas.getBoundingClientRect();const width=Math.max(320,Math.floor(rect.width||canvas.width));const height=Math.max(220,Math.floor(rect.height||canvas.height));if(canvas.width!==width*dpr||canvas.height!==height*dpr){canvas.width=width*dpr;canvas.height=height*dpr;}const ctx=canvas.getContext("2d");if(!ctx)return null;ctx.setTransform(dpr,0,0,dpr,0,0);canvas.dataset.cssWidth=String(width);canvas.dataset.cssHeight=String(height);return ctx;}
function getCanvasMetrics(ctx){const width=Number(ctx.canvas.dataset.cssWidth)||ctx.canvas.clientWidth||320;const height=Number(ctx.canvas.dataset.cssHeight)||ctx.canvas.clientHeight||220;return {w:width,h:height};}
function clearCanvas(ctx){const {w,h}=getCanvasMetrics(ctx);ctx.clearRect(0,0,w,h);}
function drawEmptyCanvasMessage(ctx,message){const {w,h}=getCanvasMetrics(ctx);ctx.fillStyle="#b8c3eb";ctx.font="14px Segoe UI";ctx.fillText(message,(w-ctx.measureText(message).width)/2,h/2);}
function buildTeamBadgeHtml(team,compact=false){const style=getTeamStyle(team);const dot=`<span class="team-dot" style="background:${escapeAttr(style.color)}"></span>`;const logo=style.logo?`<img class="team-logo" src="${escapeAttr(style.logo)}" alt="Logo ${escapeAttr(team)}" />`:"";const name=compact?escapeHtml(team):`<strong>${escapeHtml(team)}</strong>`;return `<span class="team-badge">${dot}${logo}<span>${name}</span></span>`;}
function hydrateEntries(){state.entries=state.entries.map((entry)=>normalizeEntry(entry));}
function normalizeEntry(entry){const occurredAt=normalizeDateTimeInput(entry?.occurredAt||entry?.date)||getNowLocalDateTimeValue();return {id:typeof entry?.id==="string"&&entry.id?entry.id:createEntryId(),season:normalizeSeasonCode(entry?.season)||getSeasonCodeFromDateTime(occurredAt)||getCurrentSeasonCode(),team:String(entry?.team||""),category:canonicalCategoryName(entry?.category)||DEFAULT_CATEGORIES[0],tag:canonicalTagName(entry?.tag)||DEFAULT_TAGS[0],score:Number(entry?.score)||0,note:typeof entry?.note==="string"?entry.note:"",occurredAt};}
function normalizeTeamStyles(){if(!state.teamStyles||typeof state.teamStyles!=="object")state.teamStyles={};state.teams.forEach((team,index)=>{const current=state.teamStyles[team]||{};const preset=DEFAULT_TEAM_PRESETS.find((item)=>item.name===team);state.teamStyles[team]={color:sanitizeHexColor(current.color,preset?.color||getDefaultTeamColor(index)),logo:typeof current.logo==="string"&&current.logo?current.logo:preset?.logo||""};});Object.keys(state.teamStyles).forEach((team)=>{if(!state.teams.includes(team))delete state.teamStyles[team];});}
function getTeamStyle(team){const index=Math.max(0,state.teams.indexOf(team));if(!state.teamStyles[team]){const preset=DEFAULT_TEAM_PRESETS.find((item)=>item.name===team);state.teamStyles[team]={color:preset?.color||getDefaultTeamColor(index),logo:preset?.logo||""};}return state.teamStyles[team];}
function getDefaultTeamColor(index){return TEAM_COLOR_PALETTE[index%TEAM_COLOR_PALETTE.length];}
function sanitizeHexColor(value,fallback){const v=String(value||"").trim();return /^#[0-9A-Fa-f]{6}$/.test(v)?v:fallback;}
function loadAppState(){const rawCurrent=localStorage.getItem(APP_STORAGE_KEY);if(rawCurrent){try{return normalizeState(JSON.parse(rawCurrent));}catch{return structuredClone(defaultState);}}for(const key of LEGACY_KEYS){const legacyRaw=localStorage.getItem(key);if(!legacyRaw)continue;try{const parsed=JSON.parse(legacyRaw);if(Array.isArray(parsed)){return {teams:[...defaultState.teams],categories:[...defaultState.categories],tags:[...defaultState.tags],teamStyles:structuredClone(defaultState.teamStyles),entries:parsed};}return normalizeState(parsed);}catch{continue;}}return structuredClone(defaultState);}
function normalizeState(input){const teams=Array.isArray(input?.teams)?input.teams.map(sanitizeName).filter(Boolean):[...defaultState.teams];const categories=Array.isArray(input?.categories)?input.categories.map(canonicalCategoryName).filter(Boolean):[...defaultState.categories];const tags=Array.isArray(input?.tags)?input.tags.map(canonicalTagName).filter(Boolean):[...defaultState.tags];const entries=Array.isArray(input?.entries)?input.entries:[...defaultState.entries];const teamStyles=input?.teamStyles&&typeof input.teamStyles==="object"?input.teamStyles:structuredClone(defaultState.teamStyles);return {teams:unique(teams.length?teams:defaultState.teams),categories:unique(categories.length?categories:defaultState.categories),tags:unique(tags.length?tags:defaultState.tags),teamStyles,entries};}
function saveState(){const payload={teams:unique(state.teams.map(sanitizeName).filter(Boolean)),categories:unique(state.categories.map(sanitizeName).filter(Boolean)),tags:unique(state.tags.map(canonicalTagName).filter(Boolean)),teamStyles:state.teamStyles};state.teams=payload.teams;state.categories=payload.categories;state.tags=payload.tags.length?payload.tags:[...DEFAULT_TAGS];normalizeTeamStyles();localStorage.setItem(APP_STORAGE_KEY,JSON.stringify(payload));LEGACY_KEYS.forEach((key)=>localStorage.removeItem(key));}
function loadSecurityState(){const raw=localStorage.getItem(ADMIN_SECURITY_KEY);if(!raw)return {password:ADMIN_FALLBACK_PASSWORD,failCount:0,lockedUntil:0};try{const parsed=JSON.parse(raw);return {password:typeof parsed.password==="string"&&parsed.password?parsed.password:ADMIN_FALLBACK_PASSWORD,failCount:Number(parsed.failCount)||0,lockedUntil:Number(parsed.lockedUntil)||0};}catch{return {password:ADMIN_FALLBACK_PASSWORD,failCount:0,lockedUntil:0};}}
async function hydrateSecurityState(){if(!window.KinshimaResultsDB||typeof window.KinshimaResultsDB.loadAdminSecurity!=="function")return;try{const stored=await window.KinshimaResultsDB.loadAdminSecurity();if(stored&&typeof stored==="object"){security={password:typeof stored.password==="string"&&stored.password?stored.password:security.password,failCount:Number(stored.failCount)||0,lockedUntil:Number(stored.lockedUntil)||0};localStorage.setItem(ADMIN_SECURITY_KEY,JSON.stringify(security));}}catch{/* ignore and keep local fallback */}}
function saveSecurityState(){localStorage.setItem(ADMIN_SECURITY_KEY,JSON.stringify(security));if(window.KinshimaResultsDB&&typeof window.KinshimaResultsDB.saveAdminSecurity==="function"){window.KinshimaResultsDB.saveAdminSecurity(security).catch(()=>{});}}
async function hydrateSecurityFromServer(){if(!hasAdminView)return false;try{const response=await fetch(ADMIN_PASSWORD_API_ENDPOINT,{method:"GET",cache:"no-store"});if(!response.ok)return false;const payload=await response.json();const remotePassword=typeof payload?.password==="string"?payload.password.trim():"";if(!remotePassword)return false;if(remotePassword!==security.password){security.password=remotePassword;security.failCount=0;security.lockedUntil=0;saveSecurityState();if(!isAdmin())syncAdminUI();}return true;}catch{return false;}}
async function pushSecurityToServer(){try{const response=await fetch(ADMIN_PASSWORD_API_ENDPOINT,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:security.password})});return response.ok;}catch{return false;}}
function startSecuritySyncTicker(){if(securitySyncTimerId){clearInterval(securitySyncTimerId);}securitySyncTimerId=setInterval(()=>{hydrateSecurityFromServer();},30000);}
function showAdminFeedback(message,type){if(!adminFeedback)return;adminFeedback.textContent=message;adminFeedback.classList.remove("hidden","success","error");adminFeedback.classList.add(type==="error"?"error":"success");}
function hasName(list,value){if(!Array.isArray(list))return false;const key=normalizeText(value);return list.some((item)=>normalizeText(item)===key);}
function ensureTaxonomyState(){if(!Array.isArray(state.categories))state.categories=[...DEFAULT_CATEGORIES];if(!Array.isArray(state.tags))state.tags=[...DEFAULT_TAGS];ensureBaseCategories();ensureBaseTags();}
function normalizeText(value){return sanitizeName(value).toLowerCase();}
function canonicalCategoryName(value){const cleaned=sanitizeName(value);if(!cleaned)return "";const mapped=CATEGORY_CANONICAL_MAP[cleaned.toLowerCase()];return mapped||cleaned;}
function canonicalTagName(value){return sanitizeName(value);}
function isMartialCategory(value){return MARTIAL_CATEGORY_SET.has(canonicalCategoryName(value));}
function isNarrativeCategory(value){return NARRATIVE_CATEGORY_SET.has(canonicalCategoryName(value));}
function getOrderedCategories(){const canonical=unique(state.categories.map((category)=>canonicalCategoryName(category)).filter(Boolean));const martial=MARTIAL_CATEGORIES.filter((category)=>canonical.includes(category));const narrative=NARRATIVE_CATEGORIES.filter((category)=>canonical.includes(category));const others=canonical.filter((category)=>!MARTIAL_CATEGORY_SET.has(category)&&!NARRATIVE_CATEGORY_SET.has(category));return [...martial,...narrative,...others];}
function ensureBaseCategories(){const canonical=unique((Array.isArray(state.categories)?state.categories:[]).map((category)=>canonicalCategoryName(category)).filter(Boolean));const extras=canonical.filter((category)=>!DEFAULT_CATEGORIES.includes(category));const final=[...DEFAULT_CATEGORIES,...extras];const changed=JSON.stringify(state.categories)!==JSON.stringify(final);if(changed)state.categories=final;return changed;}
function getOrderedTags(){const canonical=unique((Array.isArray(state.tags)?state.tags:[]).map((tag)=>canonicalTagName(tag)).filter(Boolean));return canonical.length?canonical:[...DEFAULT_TAGS];}
function ensureBaseTags(){const ordered=getOrderedTags();const changed=JSON.stringify(state.tags)!==JSON.stringify(ordered);if(changed)state.tags=ordered;return changed;}
function getSelectedScoreScope(){const value=scoreScopeSelect?.value;return value==="martial"||value==="narrative"?value:"global";}
function getSelectedActiveCategory(){return activeCategorySelect?.value||"all";}
function getSelectedActiveTag(){return activeTagSelect?.value||"all";}
function getCategoriesForScope(scope){const ordered=getOrderedCategories();if(scope==="martial")return ordered.filter((category)=>isMartialCategory(category));if(scope==="narrative")return ordered.filter((category)=>isNarrativeCategory(category));return ordered;}
function filterEntriesByScoreScope(entries,scope){if(scope==="martial")return entries.filter((entry)=>isMartialCategory(entry.category));if(scope==="narrative")return entries.filter((entry)=>isNarrativeCategory(entry.category));return entries;}
function filterEntriesByMainView(entries,scope){const categoryFilter=getSelectedActiveCategory();const tagFilter=getSelectedActiveTag();return filterEntriesByScoreScope(entries,scope).filter((entry)=>categoryFilter==="all"||entry.category===categoryFilter).filter((entry)=>tagFilter==="all"||entry.tag===tagFilter);}
function scopeLabel(scope){if(scope==="martial")return "martiaux";if(scope==="narrative")return "narratifs";return "globaux";}
function updateChartTitles(){const scope=getSelectedScoreScope();if(seasonProgressTitle)seasonProgressTitle.textContent=`Progression ${scopeLabel(scope)} dans le temps (saison active)`;if(globalPointsTitle)globalPointsTitle.textContent=`Points ${scopeLabel(scope)} tous temps`;}
function enforceScopeFilterCompatibility(){const scope=getSelectedScoreScope();if(scope==="global")return;const allowedCategories=getCategoriesForScope(scope);[activeCategorySelect,filterCategory].forEach((select)=>{if(!select||select.value==="all")return;if(!allowedCategories.includes(select.value))select.value="all";});}
async function migrateLegacyCategoriesIfNeeded(){const normalizedCategories=unique((Array.isArray(state.categories)?state.categories:[]).map((category)=>canonicalCategoryName(category)).filter(Boolean));const extras=normalizedCategories.filter((category)=>!DEFAULT_CATEGORIES.includes(category));const finalCategories=[...DEFAULT_CATEGORIES,...extras];const finalTags=getOrderedTags();const normalizedEntries=state.entries.map((entry)=>{const mappedCategory=canonicalCategoryName(entry.category)||DEFAULT_CATEGORIES[0];const mappedTag=canonicalTagName(entry.tag)||DEFAULT_TAGS[0];if(mappedCategory===entry.category&&mappedTag===entry.tag)return entry;return {...entry,category:mappedCategory,tag:mappedTag};});const categoriesChanged=JSON.stringify(state.categories)!==JSON.stringify(finalCategories);const tagsChanged=JSON.stringify(state.tags)!==JSON.stringify(finalTags);const entriesChanged=normalizedEntries.some((entry,index)=>entry!==state.entries[index]);if(!categoriesChanged&&!tagsChanged&&!entriesChanged)return;state.categories=finalCategories;state.tags=finalTags;state.entries=normalizedEntries;await persistEntries();}
function getSeasonList(entries){const set=new Set(entries.map((entry)=>normalizeSeasonCode(entry.season)).filter(Boolean));set.add(getCurrentSeasonCode());return Array.from(set).sort((a,b)=>seasonToYear(b)-seasonToYear(a));}
function normalizeSeasonCode(value){if(!value)return "";const cleaned=String(value).trim().toUpperCase();if(!/^LK\d{2}$/.test(cleaned))return "";return cleaned;}
function getCurrentSeasonCode(){const year=new Date().getFullYear();return `LK${String(year).slice(-2)}`;}
function getSeasonCodeFromDateTime(dateText){if(!dateText||!dateText.includes("-"))return "";const year=Number(dateText.slice(0,4));if(Number.isNaN(year))return "";return `LK${String(year).slice(-2)}`;}
function seasonToYear(seasonCode){const year2=Number(String(seasonCode).replace("LK",""));if(Number.isNaN(year2))return 0;return 2000+year2;}
function normalizeDateTimeInput(value){const raw=String(value||"").trim();if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return `${raw}T00:00`;if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(raw))return raw;if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(raw))return raw.slice(0,16);return "";}
function getNowLocalDateTimeValue(){const now=new Date();const local=new Date(now.getTime()-now.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
function formatDateTime(value){const normalized=normalizeDateTimeInput(value);if(!normalized)return "-";const [datePart,timePart]=normalized.split("T");const [year,month,day]=datePart.split("-");return `${day}/${month}/${year} ${timePart}`;}
function sanitizeName(value){return String(value||"").trim().replace(/\s+/g," ");}
function unique(items){return Array.from(new Set(items));}
function createEntryId(){if(window.crypto&&typeof window.crypto.randomUUID==="function")return window.crypto.randomUUID();return `res-${Date.now()}-${Math.random().toString(16).slice(2,10)}`;}
function escapeCsvCell(value){const raw=String(value??"");if(/[",\n]/.test(raw))return `"${raw.replace(/"/g,'""')}"`;return raw;}
function parseResultsCsv(text){const clean=String(text||"").replace(/^\uFEFF/,"");const rows=parseCsvRows(clean);if(!rows.length)return [];const headers=rows[0].map((h)=>String(h||"").trim());const idx={id:headers.indexOf("id"),occurredAt:headers.indexOf("occurredAt"),season:headers.indexOf("season"),team:headers.indexOf("team"),category:headers.indexOf("category"),tag:headers.indexOf("tag"),score:headers.indexOf("score"),note:headers.indexOf("note")};const required=["occurredAt","season","team","category","score"];if(required.some((k)=>idx[k]===-1))return [];return rows.slice(1).filter((row)=>row.some((cell)=>String(cell||"").trim()!=="")).map((row)=>({id:idx.id>=0?String(row[idx.id]||"").trim():"",occurredAt:String(row[idx.occurredAt]||"").trim(),season:String(row[idx.season]||"").trim(),team:String(row[idx.team]||"").trim(),category:String(row[idx.category]||"").trim(),tag:idx.tag>=0?String(row[idx.tag]||"").trim():DEFAULT_TAGS[0],score:Number(String(row[idx.score]||"0").replace(",",".")),note:idx.note>=0?String(row[idx.note]||"").trim():""})).filter((entry)=>normalizeSeasonCode(entry.season)&&normalizeDateTimeInput(entry.occurredAt)&&entry.team&&entry.category&&Number.isFinite(entry.score)&&entry.score>=0);}
function parseCsvRows(text){const rows=[];let row=[];let value="";let inQuotes=false;for(let i=0;i<text.length;i+=1){const ch=text[i];if(inQuotes){if(ch==='"'){if(text[i+1]==='"'){value+='"';i+=1;}else{inQuotes=false;}}else{value+=ch;}continue;}if(ch==='"'){inQuotes=true;continue;}if(ch===","){row.push(value);value="";continue;}if(ch==="\n"){row.push(value);rows.push(row);row=[];value="";continue;}if(ch==="\r"){continue;}value+=ch;}if(value!==""||row.length){row.push(value);rows.push(row);}return rows;}
function mergeImportedEntries(existing,imported){const merged=[...existing];const indexById=new Map();const indexByFingerprint=new Map();merged.forEach((entry,index)=>{if(entry.id)indexById.set(entry.id,index);indexByFingerprint.set(entryFingerprint(entry),index);});imported.forEach((entry)=>{const byId=entry.id?indexById.get(entry.id):-1;const byFingerprint=indexByFingerprint.get(entryFingerprint(entry));const targetIndex=typeof byId==="number"&&byId>=0?byId:typeof byFingerprint==="number"&&byFingerprint>=0?byFingerprint:-1;if(targetIndex>=0){merged[targetIndex]={...merged[targetIndex],...entry};return;}merged.unshift(entry);const newIndex=0;if(entry.id)indexById.set(entry.id,newIndex);indexByFingerprint.set(entryFingerprint(entry),newIndex);});return merged;}
function entryFingerprint(entry){return [normalizeDateTimeInput(entry.occurredAt)||"",String(entry.season||""),String(entry.team||""),String(entry.category||""),String(entry.tag||DEFAULT_TAGS[0]),String(entry.score??""),String(entry.note||"")].join("|");}
function readFileAsDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||""));reader.onerror=()=>reject(new Error("read-error"));reader.readAsDataURL(file);});}
function escapeHtml(value){return String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");}
function escapeAttr(value){return escapeHtml(value).replace(/`/g,"&#96;");}
async function bootstrapEntriesStorage(){if(window.KinshimaResultsDB&&typeof window.KinshimaResultsDB.bootstrapEntriesStorage==="function"){state.entries=await window.KinshimaResultsDB.bootstrapEntriesStorage({currentEntries:state.entries,defaultEntries:defaultState.entries,normalizeEntry});saveState();return;}state.entries=state.entries.map((entry)=>normalizeEntry(entry));saveState();}
async function persistEntries(){state.entries=state.entries.map((entry)=>normalizeEntry(entry));if(window.KinshimaResultsDB&&typeof window.KinshimaResultsDB.persistEntries==="function"){state.entries=await window.KinshimaResultsDB.persistEntries({entries:state.entries,normalizeEntry});}saveState();}
